## Practical Pandas: Build an End-to-End Data Analysis Project

* Master data cleaning, transformation, and analysis with this hands-on Pandas project.

## Section A: Data Loading & Inspection (1–10)

In [1]:
# Load the CSV file into a Pandas DataFrame.

import pandas as pd
df = pd.read_csv(f"C://Users//Abhinav kumar//Downloads//employee_pandas_practice.csv")
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [3]:
# Display the first 7 rows of the DataFrame.

df.head(7)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single

In [4]:
# Display the last 5 rows of the DataFrame.

df.tail()

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [5]:
# Check the shape of the DataFrame.

df.shape

(20, 15)

In [6]:
# Print column names as a Python list.

df.columns.tolist()

['id',
 'name',
 'age',
 'gender',
 'city',
 'salary',
 'department',
 'experience',
 'rating',
 'is_active',
 'projects',
 'leaves_taken',
 'bonus_percent',
 'education',
 'marital_status']

In [7]:
# Display data types of all columns.

df.dtypes

id                  int64
name                  str
age               float64
gender                str
city                  str
salary            float64
department            str
experience          int64
rating            float64
is_active            bool
projects          float64
leaves_taken      float64
bonus_percent     float64
education             str
marital_status        str
dtype: object

In [8]:
# Show complete DataFrame information.

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              20 non-null     int64
 1   name            20 non-null     str
 2   age             19 non-null     float64
 3   gender          20 non-null     str
 4   city            20 non-null     str
 5   salary          19 non-null     float64
 6   department      20 non-null     str
 7   experience      20 non-null     int64
 8   rating          19 non-null     float64
 9   is_active       20 non-null     bool
 10  projects        19 non-null     float64
 11  leaves_taken    19 non-null     float64
 12  bonus_percent   18 non-null     float64
 13  education       20 non-null     str
 14  marital_status  20 non-null     str
dtypes: bool(1), float64(6), int64(2), str(6)
memory usage: 3.0 KB

In [9]:
# Display summary statistics for numeric columns.

df.describe()

,id,age,salary,experience,rating,projects,leaves_taken,bonus_percent
count,20.00000,19.000000,19.000000,20.000000,19.000000,19.000000,19.000000,18.000000
mean,10.50000,38.684211,75526.315789,7.100000,4.305263,6.368421,7.105263,13.055556
std,5.91608,19.032290,46348.161202,4.290749,0.991337,6.084685,3.665071,3.917866
min,1.00000,23.000000,35000.000000,1.000000,3.300000,2.000000,1.000000,7.000000
25%,5.75000,28.500000,50500.000000,3.750000,3.850000,3.500000,4.000000,10.000000
50%,10.50000,34.000000,66000.000000,6.500000,4.100000,5.000000,7.000000,12.500000
75%,15.25000,40.500000,87000.000000,10.250000,4.450000,7.000000,10.000000,15.750000
max,20.00000,110.000000,250000.000000,15.000000,8.000000,30.000000,13.000000,20.000000

In [2]:
# Display summary statistics for categorical columns.

df.describe(include='object')

            name gender   city department education marital_status
count         20     20     20         20        20             20
unique        20      2      5          5         5              2
top     Person_1   Male  Delhi         IT     BTech         Single
freq           1     10      4          4         4             10

In [11]:
# Check total memory usage of the DataFrame.

df.memory_usage(deep=True).sum()

np.int64(3093)

## Section B: Column Selection & Data Types (11–20)

Mastered handling missing values and duplicates to ensure clean, reliable data.

Learned to shape, merge, and group datasets effectively to uncover deep analytical insights.

In [12]:
# Select only numeric columns from the DataFrame.

df.select_dtypes(include='number')

,id,age,salary,experience,rating,projects,leaves_taken,bonus_percent
0,1,25.0,45000.0,2,4.2,3.0,5.0,10.0
1,2,32.0,55000.0,5,3.8,5.0,10.0,12.0
2,3,41.0,NaN,8,4.5,6.0,7.0,15.0
3,4,29.0,60000.0,3,NaN,4.0,3.0,9.0
4,5,36.0,250000.0,10,4.8,7.0,12.0,18.0
5,6,27.0,50000.0,4,4.1,2.0,6.0,NaN
6,7,45.0,92000.0,11,3.9,8.0,8.0,14.0
7,8,52.0,67000.0,6,4.3,5.0,4.0,10.0
8,9,NaN,48000.0,2,3.5,3.0,2.0,8.0
9,10,28.0,90000.0,12,8.0,30.0,11.0,17.0
10,11,40.0,76000.0,7,4.4,6.0,9.0,16.0
11,12,34.0,51000.0,5,3.7,4.0,NaN,12.0
12,13,23.0,35000.0,1,3.3,2.0,1.0,7.0
13,14,110.0,98000.0,15,4.9,8.0,13.0,20.0
14,15,37.0,66000.0,9,4.0,5.0,7.0,13.0
15,16,26.0,43000.0,3,3.6,3.0,3.0,9.0
16,17,48.0,95000.0,14,4.6,7.0,12.0,19.0
17,18,39.0,72000.0,8,4.1,NaN,8.0,15.0
18,19,30.0,58000.0,4,3.9,4.0,4.0,11.0
19,20,33.0,84000.0,13,4.2,9.0,10.0,NaN

In [3]:
# Select only categorical (object) columns.

df.select_dtypes(include='object')

         name  gender       city department education marital_status
0    Person_1    Male      Delhi         IT     BTech         Single
1    Person_2  Female     Mumbai         HR       MBA        Married
2    Person_3    Male    Kolkata    Finance       MCA         Single
3    Person_4  Female    Chennai  Marketing       BSc        Married
4    Person_5    Male  Bangalore      Admin        BA         Single
5    Person_6  Female      Delhi         IT     BTech        Married
6    Person_7    Male     Mumbai         HR       MBA         Single
7    Person_8  Female    Kolkata    Finance       MCA        Married
8    Person_9    Male    Chennai  Marketing       BSc         Single
9   Person_10  Female  Bangalore      Admin        BA        Married
10  Person_11    Male      Delhi         IT     BTech         Single
11  Person_12  Female     Mumbai         HR       MBA        Married
12  Person_13    Male    Kolkata    Finance       MCA         Single
13  Person_14  Female    Chennai  Marketing       BSc        Married
14  Person_15    Male  Bangalore      Admin        BA         Single
15  Person_16  Female      Delhi         IT     BTech        Married
16  Person_17    Male     Mumbai         HR       MBA         Single
17  Person_18  Female    Kolkata    Finance       MCA        Married
18  Person_19    Male    Chennai  Marketing       BSc         Single
19  Person_20  Female  Bangalore      Admin        BA        Married

In [14]:
# Select boolean columns only.

df.select_dtypes(include='bool')

    is_active
0        True
1       False
2        True
3        True
4       False
5        True
6       False
7        True
8       False
9        True
10       True
11      False
12       True
13       True
14      False
15       True
16      False
17       True
18      False
19       True

In [15]:
# Select all columns except numeric ones.

df.select_dtypes(exclude='number')

,name,gender,city,department,is_active,education,marital_status
0,Person_1,Male,Delhi,IT,True,BTech,Single
1,Person_2,Female,Mumbai,HR,False,MBA,Married
2,Person_3,Male,Kolkata,Finance,True,MCA,Single
3,Person_4,Female,Chennai,Marketing,True,BSc,Married
4,Person_5,Male,Bangalore,Admin,False,BA,Single
5,Person_6,Female,Delhi,IT,True,BTech,Married
6,Person_7,Male,Mumbai,HR,False,MBA,Single
7,Person_8,Female,Kolkata,Finance,True,MCA,Married
8,Person_9,Male,Chennai,Marketing,False,BSc,Single
9,Person_10,Female,Bangalore,Admin,True,BA,Married
10,Person_11,Male,Delhi,IT,True,BTech,Single
11,Person_12,Female,Mumbai,HR,False,MBA,Married
12,Person_13,Male,Kolkata,Finance,True,MCA,Single
13,Person_14,Female,Chennai,Marketing,True,BSc,Married
14,Person_15,Male,Bangalore,Admin,False,BA,Single
15,Person_16,Female,Delhi,IT,True,BTech,Married
16,Person_17,Male,Mumbai,HR,False,MBA,Single
17,Person_18,Female,Kolkata,Finance,True,MCA,Married
18,Person_19,Male,Chennai,Marketing,False,BSc,Single
19,Person_20,Female,Bangalore,Admin,True,BA,Married

In [16]:
# Select the name, city, and salary columns.

df[['name', 'city', 'salary']]

         name       city    salary
0    Person_1      Delhi   45000.0
1    Person_2     Mumbai   55000.0
2    Person_3    Kolkata       NaN
3    Person_4    Chennai   60000.0
4    Person_5  Bangalore  250000.0
5    Person_6      Delhi   50000.0
6    Person_7     Mumbai   92000.0
7    Person_8    Kolkata   67000.0
8    Person_9    Chennai   48000.0
9   Person_10  Bangalore   90000.0
10  Person_11      Delhi   76000.0
11  Person_12     Mumbai   51000.0
12  Person_13    Kolkata   35000.0
13  Person_14    Chennai   98000.0
14  Person_15  Bangalore   66000.0
15  Person_16      Delhi   43000.0
16  Person_17     Mumbai   95000.0
17  Person_18    Kolkata   72000.0
18  Person_19    Chennai   58000.0
19  Person_20  Bangalore   84000.0

In [17]:
# Select the first 5 columns using positional indexing.

df.iloc[:, :5]

    id       name    age  gender       city
0    1   Person_1   25.0    Male      Delhi
1    2   Person_2   32.0  Female     Mumbai
2    3   Person_3   41.0    Male    Kolkata
3    4   Person_4   29.0  Female    Chennai
4    5   Person_5   36.0    Male  Bangalore
5    6   Person_6   27.0  Female      Delhi
6    7   Person_7   45.0    Male     Mumbai
7    8   Person_8   52.0  Female    Kolkata
8    9   Person_9    NaN    Male    Chennai
9   10  Person_10   28.0  Female  Bangalore
10  11  Person_11   40.0    Male      Delhi
11  12  Person_12   34.0  Female     Mumbai
12  13  Person_13   23.0    Male    Kolkata
13  14  Person_14  110.0  Female    Chennai
14  15  Person_15   37.0    Male  Bangalore
15  16  Person_16   26.0  Female      Delhi
16  17  Person_17   48.0    Male     Mumbai
17  18  Person_18   39.0  Female    Kolkata
18  19  Person_19   30.0    Male    Chennai
19  20  Person_20   33.0  Female  Bangalore

In [18]:
# Select alternate columns (every second column).

df.iloc[:, ::2]

,id,age,city,department,rating,projects,bonus_percent,marital_status
0,1,25.0,Delhi,IT,4.2,3.0,10.0,Single
1,2,32.0,Mumbai,HR,3.8,5.0,12.0,Married
2,3,41.0,Kolkata,Finance,4.5,6.0,15.0,Single
3,4,29.0,Chennai,Marketing,NaN,4.0,9.0,Married
4,5,36.0,Bangalore,Admin,4.8,7.0,18.0,Single
5,6,27.0,Delhi,IT,4.1,2.0,NaN,Married
6,7,45.0,Mumbai,HR,3.9,8.0,14.0,Single
7,8,52.0,Kolkata,Finance,4.3,5.0,10.0,Married
8,9,NaN,Chennai,Marketing,3.5,3.0,8.0,Single
9,10,28.0,Bangalore,Admin,8.0,30.0,17.0,Married
10,11,40.0,Delhi,IT,4.4,6.0,16.0,Single
11,12,34.0,Mumbai,HR,3.7,4.0,12.0,Married
12,13,23.0,Kolkata,Finance,3.3,2.0,7.0,Single
13,14,110.0,Chennai,Marketing,4.9,8.0,20.0,Married
14,15,37.0,Bangalore,Admin,4.0,5.0,13.0,Single
15,16,26.0,Delhi,IT,3.6,3.0,9.0,Married
16,17,48.0,Mumbai,HR,4.6,7.0,19.0,Single
17,18,39.0,Kolkata,Finance,4.1,NaN,15.0,Married
18,19,30.0,Chennai,Marketing,3.9,4.0,11.0,Single
19,20,33.0,Bangalore,Admin,4.2,9.0,NaN,Married

In [19]:
# Convert department column to category data type.

df['department'] = df['department'].astype('category')
df['department']

0            IT
1            HR
2       Finance
3     Marketing
4         Admin
5            IT
6            HR
7       Finance
8     Marketing
9         Admin
10           IT
11           HR
12      Finance
13    Marketing
14        Admin
15           IT
16           HR
17      Finance
18    Marketing
19        Admin
Name: department, dtype: category
Categories (5, str): ['Admin', 'Finance', 'HR', 'IT', 'Marketing']

In [20]:
# Convert salary column to float explicitly.

df['salary'] = df['salary'].astype(float)
df['salary']

0      45000.0
1      55000.0
2          NaN
3      60000.0
4     250000.0
5      50000.0
6      92000.0
7      67000.0
8      48000.0
9      90000.0
10     76000.0
11     51000.0
12     35000.0
13     98000.0
14     66000.0
15     43000.0
16     95000.0
17     72000.0
18     58000.0
19     84000.0
Name: salary, dtype: float64

In [21]:
# Select columns whose data type is float.

df.select_dtypes(include='float')

      age    salary  rating  projects  leaves_taken  bonus_percent
0    25.0   45000.0     4.2       3.0           5.0           10.0
1    32.0   55000.0     3.8       5.0          10.0           12.0
2    41.0       NaN     4.5       6.0           7.0           15.0
3    29.0   60000.0     NaN       4.0           3.0            9.0
4    36.0  250000.0     4.8       7.0          12.0           18.0
5    27.0   50000.0     4.1       2.0           6.0            NaN
6    45.0   92000.0     3.9       8.0           8.0           14.0
7    52.0   67000.0     4.3       5.0           4.0           10.0
8     NaN   48000.0     3.5       3.0           2.0            8.0
9    28.0   90000.0     8.0      30.0          11.0           17.0
10   40.0   76000.0     4.4       6.0           9.0           16.0
11   34.0   51000.0     3.7       4.0           NaN           12.0
12   23.0   35000.0     3.3       2.0           1.0            7.0
13  110.0   98000.0     4.9       8.0          13.0           20.0
14   37.0   66000.0     4.0       5.0           7.0           13.0
15   26.0   43000.0     3.6       3.0           3.0            9.0
16   48.0   95000.0     4.6       7.0          12.0           19.0
17   39.0   72000.0     4.1       NaN           8.0           15.0
18   30.0   58000.0     3.9       4.0           4.0           11.0
19   33.0   84000.0     4.2       9.0          10.0            NaN

## Section C: Missing Value Analysis (21–35)

* Tracked down missing data patterns to prevent errors in our analysis.
* Filled or removed gaps cleanly so the final insights are accurate and trustworthy.

In [22]:
# Count missing values in each column.

df.isnull().sum()

id                0
name              0
age               1
gender            0
city              0
salary            1
department        0
experience        0
rating            1
is_active         0
projects          1
leaves_taken      1
bonus_percent     2
education         0
marital_status    0
dtype: int64

In [23]:
# Find total number of missing values in the DataFrame.

df.isnull().sum().sum()

np.int64(7)

In [24]:
# Identify rows where salary is missing.

df[df['salary'].isnull()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single

In [25]:
# Identify rows having at least one missing value.

df[df.isnull().any(axis=1)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [26]:
# Identify rows where all values are present.

df[df.notnull().all(axis=1)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single

In [27]:
# Fill missing age values with the column mean.

df['age'] = df['age'].fillna(df['age'].mean())
df['age']

0      25.000000
1      32.000000
2      41.000000
3      29.000000
4      36.000000
5      27.000000
6      45.000000
7      52.000000
8      38.684211
9      28.000000
10     40.000000
11     34.000000
12     23.000000
13    110.000000
14     37.000000
15     26.000000
16     48.000000
17     39.000000
18     30.000000
19     33.000000
Name: age, dtype: float64

In [28]:
# Fill missing salary values with the column median.

df['salary'] = df['salary'].fillna(df['salary'].median())
df['salary']

0      45000.0
1      55000.0
2      66000.0
3      60000.0
4     250000.0
5      50000.0
6      92000.0
7      67000.0
8      48000.0
9      90000.0
10     76000.0
11     51000.0
12     35000.0
13     98000.0
14     66000.0
15     43000.0
16     95000.0
17     72000.0
18     58000.0
19     84000.0
Name: salary, dtype: float64

In [29]:
# Fill missing categorical values with "Unknown".

df = df.fillna({'column_name': 'Unknown'})
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [30]:
# Forward-fill missing values.

df = df.ffill()
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married

In [31]:
# Backward-fill missing values.

df = df.bfill()
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married

In [32]:
# Fill missing bonus_percent using department-wise mean.

df['bonus_percent'] = df['bonus_percent'].fillna(
    df.groupby('department', observed=True)['bonus_percent'].transform('mean'))
df['bonus_percent']

0     10.0
1     12.0
2     15.0
3      9.0
4     18.0
5     18.0
6     14.0
7     10.0
8      8.0
9     17.0
10    16.0
11    12.0
12     7.0
13    20.0
14    13.0
15     9.0
16    19.0
17    15.0
18    11.0
19    11.0
Name: bonus_percent, dtype: float64

In [33]:
# Drop rows where rating is missing.

df = df.dropna(subset=['rating'])
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married

In [34]:
# Drop columns having more than 2 missing values.

df = df.dropna(axis=1, thresh=len(df) - 2)
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.000000,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married

In [35]:
# Create a new column indicating whether salary was missing.

df['salary_was_missing'] = df['salary'].isnull()
df['salary_was_missing']

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: salary_was_missing, dtype: bool

In [53]:
# # Replace all remaining missing values with 0.

df1=df.fillna(0)
df1

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
9,10,Person_10,28.000000,Female,Bangalore,0.873016,Admin,12,8.0,True,11.1,11.0,17.0,BA,Married,False,False,0.873016
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778

## Section D: Outlier Detection & Treatment (36–50)

* Used the IQR method to spot and fix extreme data points.

* Cleaned out unusual values to make sure the results aren't distorted.

In [37]:
# Detect outliers in age using the IQR method.

Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['age'] < lower) | (df['age'] > upper)]
outliers

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False

In [38]:
# Detect outliers in salary using the IQR method.

Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df['salary'] < lower) | (df['salary'] > upper)]
outliers

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single,False

In [39]:
# Identify rows where projects is an outlier.

Q1 = df['projects'].quantile(0.25)
Q3 = df['projects'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[(df['projects'] < lower) | (df['projects'] > upper)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,False

In [40]:
# Create a new column flagging salary outliers.

Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df['salary_outlier'] = ((df['salary'] < lower) | (df['salary'] > upper))
df['salary_outlier']

0     False
1     False
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: salary_outlier, dtype: bool

In [41]:
# Remove rows containing salary outliers.

df = df[~df['salary_outlier']]
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier
0,1,Person_1,25.000000,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False
1,2,Person_2,32.000000,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False
2,3,Person_3,41.000000,Male,Kolkata,66000.0,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False
3,4,Person_4,29.000000,Female,Chennai,60000.0,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False
5,6,Person_6,27.000000,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False
6,7,Person_7,45.000000,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False
7,8,Person_8,52.000000,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False
8,9,Person_9,38.684211,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False
9,10,Person_10,28.000000,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,False,False
10,11,Person_11,40.000000,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False
11,12,Person_12,34.000000,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False
12,13,Person_13,23.000000,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False
13,14,Person_14,110.000000,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False
14,15,Person_15,37.000000,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False
15,16,Person_16,26.000000,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False
16,17,Person_17,48.000000,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False
17,18,Person_18,39.000000,Female,Kolkata,72000.0,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False
18,19,Person_19,30.000000,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False
19,20,Person_20,33.000000,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False

In [42]:
# Cap salary outliers using upper and lower IQR limits.

Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df['salary'] = df['salary'].clip(lower, upper)
df['salary']

0     45000.0
1     55000.0
2     66000.0
3     60000.0
5     50000.0
6     92000.0
7     67000.0
8     48000.0
9     90000.0
10    76000.0
11    51000.0
12    35000.0
13    98000.0
14    66000.0
15    43000.0
16    95000.0
17    72000.0
18    58000.0
19    84000.0
Name: salary, dtype: float64

In [43]:
# Replace age outliers with median age.

Q1 = df['age'].quantile(0.25)
Q3 = df['age'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

median_age = df['age'].median()

df.loc[(df['age'] < lower) | (df['age'] > upper), 'age'] = median_age

In [44]:
# Detect outliers in rating.

Q1 = df['rating'].quantile(0.25)
Q3 = df['rating'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[(df['rating'] < lower) | (df['rating'] > upper)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,False,False

In [45]:
# Detect department-wise salary outliers.

def detect_outliers(group):
    Q1 = group['salary'].quantile(0.25)
    Q3 = group['salary'].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return group[(group['salary'] < lower) | (group['salary'] > upper)]

df.groupby('department', observed=True, group_keys=False)\
  .apply(detect_outliers, include_groups=False)

,id,name,age,gender,city,salary,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier
12,13,Person_13,23.0,Male,Kolkata,35000.0,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False
10,11,Person_11,40.0,Male,Delhi,76000.0,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False
13,14,Person_14,34.0,Female,Chennai,98000.0,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False

In [46]:
# Count number of outliers in each numeric column.

num_cols = df.select_dtypes(include='number').columns

outlier_counts = {}

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outlier_counts[col] = ((df[col] < lower) | (df[col] > upper)).sum()

outlier_counts

{'id': np.int64(0),
 'age': np.int64(0),
 'salary': np.int64(0),
 'experience': np.int64(0),
 'rating': np.int64(1),
 'projects': np.int64(1),
 'leaves_taken': np.int64(0),
 'bonus_percent': np.int64(0)}

In [47]:
# Identify rows having more than one outlier.

num_cols = df.select_dtypes(include='number').columns

outlier_flag = pd.DataFrame()

for col in num_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    outlier_flag[col] = (df[col] < lower) | (df[col] > upper)

# Rows with more than 1 outlier
df[outlier_flag.sum(axis=1) > 1]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,False,False

In [49]:
# Replace outliers in projects with the 95th percentile.

Q1 = df['projects'].quantile(0.25)
Q3 = df['projects'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

p95 = df['projects'].quantile(0.95)

df.loc[(df['projects'] < lower) | (df['projects'] > upper), 'projects'] = p95

In [50]:
#Normalize salary after outlier treatment.

df['salary'] = (df['salary'] - df['salary'].min()) / (df['salary'].max() - df['salary'].min())
df['salary']

0     0.158730
1     0.317460
2     0.492063
3     0.396825
5     0.238095
6     0.904762
7     0.507937
8     0.206349
9     0.873016
10    0.650794
11    0.253968
12    0.000000
13    1.000000
14    0.492063
15    0.126984
16    0.952381
17    0.587302
18    0.365079
19    0.777778
Name: salary, dtype: float64

In [51]:
# Compare salary before and after capping.

# Step 1: Original salary save karo
df['salary_before'] = df['salary']

# Step 2: Capping karo
Q1 = df['salary'].quantile(0.25)
Q3 = df['salary'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df['salary'] = df['salary'].clip(lower, upper)

# Step 3: Compare
df[['salary_before', 'salary']]

    salary_before    salary
0        0.158730  0.158730
1        0.317460  0.317460
2        0.492063  0.492063
3        0.396825  0.396825
5        0.238095  0.238095
6        0.904762  0.904762
7        0.507937  0.507937
8        0.206349  0.206349
9        0.873016  0.873016
10       0.650794  0.650794
11       0.253968  0.253968
12       0.000000  0.000000
13       1.000000  1.000000
14       0.492063  0.492063
15       0.126984  0.126984
16       0.952381  0.952381
17       0.587302  0.587302
18       0.365079  0.365079
19       0.777778  0.777778

In [52]:
#Create a clean DataFrame with no outliers.

num_cols = df.select_dtypes(include='number').columns

clean_df = df.copy()

for col in num_cols:
    Q1 = clean_df[col].quantile(0.25)
    Q3 = clean_df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    clean_df = clean_df[(clean_df[col] >= lower) & (clean_df[col] <= upper)]

clean_df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_was_missing,salary_outlier,salary_before
0,1,Person_1,25.000000,Male,Delhi,0.158730,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,False,False,0.158730
1,2,Person_2,32.000000,Female,Mumbai,0.317460,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,False,False,0.317460
2,3,Person_3,41.000000,Male,Kolkata,0.492063,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,False,False,0.492063
3,4,Person_4,29.000000,Female,Chennai,0.396825,Marketing,3,4.5,True,4.0,3.0,9.0,BSc,Married,False,False,0.396825
5,6,Person_6,27.000000,Female,Delhi,0.238095,IT,4,4.1,True,2.0,6.0,18.0,BTech,Married,False,False,0.238095
6,7,Person_7,45.000000,Male,Mumbai,0.904762,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,False,False,0.904762
7,8,Person_8,52.000000,Female,Kolkata,0.507937,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,False,False,0.507937
8,9,Person_9,38.684211,Male,Chennai,0.206349,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,False,False,0.206349
10,11,Person_11,40.000000,Male,Delhi,0.650794,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,False,False,0.650794
11,12,Person_12,34.000000,Female,Mumbai,0.253968,HR,5,3.7,False,4.0,9.0,12.0,MBA,Married,False,False,0.253968
12,13,Person_13,23.000000,Male,Kolkata,0.000000,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,False,False,0.000000
13,14,Person_14,34.000000,Female,Chennai,1.000000,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,False,False,1.000000
14,15,Person_15,37.000000,Male,Bangalore,0.492063,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,False,False,0.492063
15,16,Person_16,26.000000,Female,Delhi,0.126984,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,False,False,0.126984
16,17,Person_17,48.000000,Male,Mumbai,0.952381,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,False,False,0.952381
17,18,Person_18,39.000000,Female,Kolkata,0.587302,Finance,8,4.1,True,7.0,8.0,15.0,MCA,Married,False,False,0.587302
18,19,Person_19,30.000000,Male,Chennai,0.365079,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,False,False,0.365079
19,20,Person_20,33.000000,Female,Bangalore,0.777778,Admin,13,4.2,True,9.0,10.0,11.0,BA,Married,False,False,0.777778