## Section E: Filtering & Conditional Selection (51–70)

* Filtered the data to keep only the useful details.

* This made analysis easier and helped in making better decisions.

In [34]:
# Load the CSV file into a Pandas DataFrame.
import pandas as pd

df = pd.read_csv(r"C://Users//Abhinav kumar//Downloads//employee_pandas_practice.csv")
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [35]:
# Filter employees whose salary is greater than 60,000.

df[df['salary'] > 60000]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [36]:
# Filter employees whose age is less than 30.

df[df['age'] < 30]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married

In [37]:
# Filter employees from Delhi or Mumbai.

df[df['city'].isin(['Delhi', 'Mumbai'])]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single

In [38]:
# Filter employees from IT department with salary > 70,000.

df[(df['department'] == 'IT') & (df['salary'] > 70000)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single

In [39]:
# Filter employees with more than 10 years of experience.

df[df['experience'] > 10]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [40]:
# Filter employees who are active.

df[df['is_active'] == True]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [41]:
# Filter employees who are inactive and married.

df[(df['is_active'] == False) & (df['marital_status'] == 'Married')]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married

In [42]:
# Filter employees whose projects count is between 3 and 7.

df[(df['projects'] >= 3) & (df['projects'] <= 7)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single

In [43]:
# Filter employees whose salary is missing.

df[df['salary'].isnull()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single

In [44]:
# Filter employees with no missing values.

df[df.notnull().all(axis=1)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single

In [45]:
# Filter employees whose rating is above average.

df[df['rating'] > df['rating'].mean()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single

In [46]:
# Filter top 5 highest-paid employees.

df.nlargest(5, 'salary')

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married

In [47]:
# Filter bottom 5 employees by rating.

df.nsmallest(5, 'rating')

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married

In [48]:
# Filter employees whose city is not Bangalore.

df[df['city'] != 'Bangalore']

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single

In [49]:
# Filter employees whose bonus percent is greater than 15.

df[df['bonus_percent'] > 15]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single

In [50]:
# Filter employees using query() method.

df.query("salary > 60000 and age < 30")

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married

In [51]:
# Filter employees using lambda function.

df[lambda x: (x['salary'] > 50000) & (x['age'] < 40)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [52]:
# Filter rows where salary is above department average.

df[df['salary'] > df.groupby('department', observed=True)['salary'].transform('mean')]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married

In [53]:
# Filter employees with maximum experience.

df[df['experience'] == df['experience'].max()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married

In [54]:
# Filter employees whose projects count is an outlier.

Q1 = df['projects'].quantile(0.25)
Q3 = df['projects'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df[(df['projects'] < lower) | (df['projects'] > upper)]

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married

## Section F: value_counts, unique, nunique (71–85)
* Explored categorical variables using frequency counts and category distributions.
* Identified key patterns and trends across different categories in the dataset.

In [55]:
# Find unique cities.

df['city'].unique()

<ArrowStringArray>
['Delhi', 'Mumbai', 'Kolkata', 'Chennai', 'Bangalore']
Length: 5, dtype: str

In [56]:
# Count number of unique departments.

df['department'].nunique()

5

In [57]:
# Find frequency of each department.

df['department'].value_counts()

department
IT           4
HR           4
Finance      4
Marketing    4
Admin        4
Name: count, dtype: int64

In [58]:
# Find city-wise employee count.

df['city'].value_counts()

city
Delhi        4
Mumbai       4
Kolkata      4
Chennai      4
Bangalore    4
Name: count, dtype: int64

In [59]:
#Find education-wise distribution.

df['education'].value_counts()

education
BTech    4
MBA      4
MCA      4
BSc      4
BA       4
Name: count, dtype: int64

In [60]:
# Calculate percentage distribution of gender.

df['gender'].value_counts(normalize=True) * 100

gender
Male      50.0
Female    50.0
Name: proportion, dtype: float64

In [61]:
# Sort department counts in ascending order.

df['department'].value_counts().sort_values(ascending=True)

department
IT           4
HR           4
Finance      4
Marketing    4
Admin        4
Name: count, dtype: int64

In [62]:
# Identify departments having more than 3 employees.

df['department'].value_counts()[df['department'].value_counts() > 3]

department
IT           4
HR           4
Finance      4
Marketing    4
Admin        4
Name: count, dtype: int64

In [63]:
# Convert value_counts output to DataFrame.

df['department'].value_counts().reset_index(name='count')

  department  count
0         IT      4
1         HR      4
2    Finance      4
3  Marketing      4
4      Admin      4

In [64]:
# Find rare education categories.

df['education'].value_counts()[df['education'].value_counts() < 2]

Series([], Name: count, dtype: int64)

In [65]:
# Count unique cities per department.

df.groupby('department', observed=True)['city'].nunique()

department
Admin        1
Finance      1
HR           1
IT           1
Marketing    1
Name: city, dtype: int64

In [66]:
# Find most common city.

df['city'].value_counts().idxmax()

'Delhi'

In [67]:
# Find least common department.

df['department'].value_counts().idxmin()

'IT'

In [68]:
# Find number of unique marital statuses.

df['marital_status'].nunique()

2

In [69]:
# Merge rare education values into "Other".

rare = df['education'].value_counts()[df['education'].value_counts() < 2].index

df['education'] = df['education'].replace(rare, 'Other')
df ['education']

0     BTech
1       MBA
2       MCA
3       BSc
4        BA
5     BTech
6       MBA
7       MCA
8       BSc
9        BA
10    BTech
11      MBA
12      MCA
13      BSc
14       BA
15    BTech
16      MBA
17      MCA
18      BSc
19       BA
Name: education, dtype: str

## Section G: Sorting & Ranking (86–100)

* Used sorting and ranking techniques to analyze trends, top and bottom values, and performance indicators.
* This helps in making data comparisons clearer and easier to understand.

In [70]:
# Sort employees by salary ascending.

df.sort_values(by='salary', ascending=True)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single

In [71]:
# Sort employees by salary descending

df.sort_values(by='salary', ascending=False)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single

In [72]:
# Sort employees by city and salary.

df.sort_values(by=['city', 'salary'])

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single

In [73]:
# Sort employees by experience descending.

df.sort_values(by='experience', ascending=False)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single

In [74]:
# Sort employees placing missing salary at the end.

df.sort_values(by='salary', na_position='last')

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single

In [75]:
# Rank employees based on salary.

df['salary_rank'] = df['salary'].rank()
df['salary_rank']

0      3.0
1      7.0
2      NaN
3      9.0
4     19.0
5      5.0
6     16.0
7     11.0
8      4.0
9     15.0
10    13.0
11     6.0
12     1.0
13    18.0
14    10.0
15     2.0
16    17.0
17    12.0
18     8.0
19    14.0
Name: salary_rank, dtype: float64

In [76]:
# Rank employees department-wise by salary.

df['dept_salary_rank'] = df.groupby('department', observed=True)['salary'].rank()
df['dept_salary_rank']

0     2.0
1     2.0
2     NaN
3     3.0
4     4.0
5     3.0
6     3.0
7     2.0
8     1.0
9     3.0
10    4.0
11    1.0
12    1.0
13    4.0
14    1.0
15    1.0
16    4.0
17    3.0
18    2.0
19    2.0
Name: dept_salary_rank, dtype: float64

In [77]:
# Rank employees based on experience.

df['experience_rank'] = df['experience'].rank()
df['experience_rank']

0      2.5
1      8.5
2     12.5
3      4.5
4     15.0
5      6.5
6     16.0
7     10.0
8      2.5
9     17.0
10    11.0
11     8.5
12     1.0
13    20.0
14    14.0
15     4.5
16    19.0
17    12.5
18     6.5
19    18.0
Name: experience_rank, dtype: float64

In [78]:
# Sort departments by average salary.

df.groupby('department', observed=True)['salary'].mean().sort_values()

department
IT            53500.0
Finance       58000.0
Marketing     66000.0
HR            73250.0
Admin        122500.0
Name: salary, dtype: float64

In [79]:
# Sort employees by number of projects.

df.sort_values(by='projects')

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_rank,dept_salary_rank,experience_rank
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married,5.0,3.0,6.5
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,1.0,1.0,1.0
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,4.0,1.0,2.5
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,3.0,2.0,2.5
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,2.0,1.0,4.5
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married,6.0,1.0,8.5
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married,9.0,3.0,4.5
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,8.0,2.0,6.5
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,10.0,1.0,14.0
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,11.0,2.0,10.0
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,7.0,2.0,8.5
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,NaN,NaN,12.5
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,13.0,4.0,11.0
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single,19.0,4.0,15.0
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,17.0,4.0,19.0
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,16.0,3.0,16.0
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,18.0,4.0,20.0
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married,14.0,2.0,18.0
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,15.0,3.0,17.0
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married,12.0,3.0,12.5

In [80]:
# Sort DataFrame by index descending.

df.sort_index(ascending=False)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_rank,dept_salary_rank,experience_rank
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married,14.0,2.0,18.0
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,8.0,2.0,6.5
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married,12.0,3.0,12.5
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,17.0,4.0,19.0
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,2.0,1.0,4.5
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,10.0,1.0,14.0
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,18.0,4.0,20.0
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,1.0,1.0,1.0
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married,6.0,1.0,8.5
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,13.0,4.0,11.0
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,15.0,3.0,17.0
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,4.0,1.0,2.5
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,11.0,2.0,10.0
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,16.0,3.0,16.0
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married,5.0,3.0,6.5
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single,19.0,4.0,15.0
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married,9.0,3.0,4.5
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,NaN,NaN,12.5
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,7.0,2.0,8.5
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,3.0,2.0,2.5

In [81]:
# Sort employees by salary-to-experience ratio.

df.assign(ratio=df['salary'] / df['experience']).sort_values(by='ratio', ascending=False)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_rank,dept_salary_rank,experience_rank,ratio
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,1.0,1.0,1.0,35000.000000
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single,19.0,4.0,15.0,25000.000000
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,4.0,1.0,2.5,24000.000000
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,3.0,2.0,2.5,22500.000000
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married,9.0,3.0,4.5,20000.000000
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,8.0,2.0,6.5,14500.000000
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,2.0,1.0,4.5,14333.333333
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married,5.0,3.0,6.5,12500.000000
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,11.0,2.0,10.0,11166.666667
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,7.0,2.0,8.5,11000.000000
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,13.0,4.0,11.0,10857.142857
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married,6.0,1.0,8.5,10200.000000
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married,12.0,3.0,12.5,9000.000000
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,16.0,3.0,16.0,8363.636364
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,15.0,3.0,17.0,7500.000000
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,10.0,1.0,14.0,7333.333333
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,17.0,4.0,19.0,6785.714286
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,18.0,4.0,20.0,6533.333333
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married,14.0,2.0,18.0,6461.538462
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,NaN,NaN,12.5,NaN

In [82]:
# Sort employees by bonus percent.

df.sort_values(by='bonus_percent')

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_rank,dept_salary_rank,experience_rank
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,1.0,1.0,1.0
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,4.0,1.0,2.5
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,2.0,1.0,4.5
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married,9.0,3.0,4.5
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,11.0,2.0,10.0
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,3.0,2.0,2.5
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,8.0,2.0,6.5
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,7.0,2.0,8.5
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married,6.0,1.0,8.5
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,10.0,1.0,14.0
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,16.0,3.0,16.0
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,NaN,NaN,12.5
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married,12.0,3.0,12.5
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,13.0,4.0,11.0
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,15.0,3.0,17.0
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single,19.0,4.0,15.0
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,17.0,4.0,19.0
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,18.0,4.0,20.0
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married,5.0,3.0,6.5
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married,14.0,2.0,18.0

In [83]:
# Sort employees by frequency of city.

df.sort_values(by='city', key=lambda x: x.map(x.value_counts()))

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_rank,dept_salary_rank,experience_rank
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,3.0,2.0,2.5
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,7.0,2.0,8.5
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,NaN,NaN,12.5
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married,9.0,3.0,4.5
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single,19.0,4.0,15.0
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married,5.0,3.0,6.5
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,16.0,3.0,16.0
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,11.0,2.0,10.0
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single,4.0,1.0,2.5
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married,15.0,3.0,17.0
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,13.0,4.0,11.0
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married,6.0,1.0,8.5
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,1.0,1.0,1.0
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married,18.0,4.0,20.0
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single,10.0,1.0,14.0
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,2.0,1.0,4.5
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,17.0,4.0,19.0
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married,12.0,3.0,12.5
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single,8.0,2.0,6.5
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married,14.0,2.0,18.0

In [84]:
# Sort employees based on custom department order.

order = ['HR', 'IT', 'Finance', 'Sales']

df['department'] = pd.Categorical(df['department'], categories=order, ordered=True)

df.sort_values(by='department')

C:\Users\Abhinav kumar\AppData\Local\Temp\ipykernel_10884\3486493685.py:5: Pandas4Warning: Constructing a Categorical with a dtype and values containing non-null entries not in that dtype's categories is deprecated and will raise in a future version.
  df['department'] = pd.Categorical(df['department'], categories=order, ordered=True)

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,salary_rank,dept_salary_rank,experience_rank
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married,7.0,2.0,8.5
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single,16.0,3.0,16.0
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married,6.0,1.0,8.5
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single,17.0,4.0,19.0
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single,3.0,2.0,2.5
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married,5.0,3.0,6.5
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single,13.0,4.0,11.0
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married,2.0,1.0,4.5
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single,NaN,NaN,12.5
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married,11.0,2.0,10.0
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single,1.0,1.0,1.0
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married,12.0,3.0,12.5
3,4,Person_4,29.0,Female,Chennai,60000.0,NaN,3,NaN,True,4.0,3.0,9.0,BSc,Married,9.0,3.0,4.5
4,5,Person_5,36.0,Male,Bangalore,250000.0,NaN,10,4.8,False,7.0,12.0,18.0,BA,Single,19.0,4.0,15.0
8,9,Person_9,NaN,Male,Chennai,48000.0,NaN,2,3.5,False,3.0,2.0,8.0,BSc,Single,4.0,1.0,2.5
9,10,Person_10,28.0,Female,Bangalore,90000.0,NaN,12,8.0,True,30.0,11.0,17.0,BA,Married,15.0,3.0,17.0
13,14,Person_14,110.0,Female,Chennai,98000.0,NaN,15,4.9,True,8.0,13.0,20.0,BSc,Married,18.0,4.0,20.0
14,15,Person_15,37.0,Male,Bangalore,66000.0,NaN,9,4.0,False,5.0,7.0,13.0,BA,Single,10.0,1.0,14.0
18,19,Person_19,30.0,Male,Chennai,58000.0,NaN,4,3.9,False,4.0,4.0,11.0,BSc,Single,8.0,2.0,6.5
19,20,Person_20,33.0,Female,Bangalore,84000.0,NaN,13,4.2,True,9.0,10.0,NaN,BA,Married,14.0,2.0,18.0