## Section H: replace, map & apply (101–115)

* Transformed dataset values efficiently using apply, map, and replace functions.

* Enabled effective feature engineering and custom data manipulation through these methods.

In [1]:
# Load the CSV file into a Pandas DataFrame.
import pandas as pd

df = pd.read_csv(r"C://Users//Abhinav kumar//Downloads//employee_pandas_practice.csv")
df

,id,name,age,gender,city,salary,department,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status
0,1,Person_1,25.0,Male,Delhi,45000.0,IT,2,4.2,True,3.0,5.0,10.0,BTech,Single
1,2,Person_2,32.0,Female,Mumbai,55000.0,HR,5,3.8,False,5.0,10.0,12.0,MBA,Married
2,3,Person_3,41.0,Male,Kolkata,NaN,Finance,8,4.5,True,6.0,7.0,15.0,MCA,Single
3,4,Person_4,29.0,Female,Chennai,60000.0,Marketing,3,NaN,True,4.0,3.0,9.0,BSc,Married
4,5,Person_5,36.0,Male,Bangalore,250000.0,Admin,10,4.8,False,7.0,12.0,18.0,BA,Single
5,6,Person_6,27.0,Female,Delhi,50000.0,IT,4,4.1,True,2.0,6.0,NaN,BTech,Married
6,7,Person_7,45.0,Male,Mumbai,92000.0,HR,11,3.9,False,8.0,8.0,14.0,MBA,Single
7,8,Person_8,52.0,Female,Kolkata,67000.0,Finance,6,4.3,True,5.0,4.0,10.0,MCA,Married
8,9,Person_9,NaN,Male,Chennai,48000.0,Marketing,2,3.5,False,3.0,2.0,8.0,BSc,Single
9,10,Person_10,28.0,Female,Bangalore,90000.0,Admin,12,8.0,True,30.0,11.0,17.0,BA,Married
10,11,Person_11,40.0,Male,Delhi,76000.0,IT,7,4.4,True,6.0,9.0,16.0,BTech,Single
11,12,Person_12,34.0,Female,Mumbai,51000.0,HR,5,3.7,False,4.0,NaN,12.0,MBA,Married
12,13,Person_13,23.0,Male,Kolkata,35000.0,Finance,1,3.3,True,2.0,1.0,7.0,MCA,Single
13,14,Person_14,110.0,Female,Chennai,98000.0,Marketing,15,4.9,True,8.0,13.0,20.0,BSc,Married
14,15,Person_15,37.0,Male,Bangalore,66000.0,Admin,9,4.0,False,5.0,7.0,13.0,BA,Single
15,16,Person_16,26.0,Female,Delhi,43000.0,IT,3,3.6,True,3.0,3.0,9.0,BTech,Married
16,17,Person_17,48.0,Male,Mumbai,95000.0,HR,14,4.6,False,7.0,12.0,19.0,MBA,Single
17,18,Person_18,39.0,Female,Kolkata,72000.0,Finance,8,4.1,True,NaN,8.0,15.0,MCA,Married
18,19,Person_19,30.0,Male,Chennai,58000.0,Marketing,4,3.9,False,4.0,4.0,11.0,BSc,Single
19,20,Person_20,33.0,Female,Bangalore,84000.0,Admin,13,4.2,True,9.0,10.0,NaN,BA,Married

In [2]:
# Replace "IT" with "Information Technology".

df['department'] = df['department'].replace('IT', 'Information Technology')
df['department']

0     Information Technology
1                         HR
2                    Finance
3                  Marketing
4                      Admin
5     Information Technology
6                         HR
7                    Finance
8                  Marketing
9                      Admin
10    Information Technology
11                        HR
12                   Finance
13                 Marketing
14                     Admin
15    Information Technology
16                        HR
17                   Finance
18                 Marketing
19                     Admin
Name: department, dtype: str

In [3]:
# Replace missing bonus percent with 0.

df['bonus_percent'] = df['bonus_percent'].fillna(0)
df['bonus_percent']

0     10.0
1     12.0
2     15.0
3      9.0
4     18.0
5      0.0
6     14.0
7     10.0
8      8.0
9     17.0
10    16.0
11    12.0
12     7.0
13    20.0
14    13.0
15     9.0
16    19.0
17    15.0
18    11.0
19     0.0
Name: bonus_percent, dtype: float64

In [4]:
# Replace rare education categories with "Other".

rare = df['education'].value_counts()[df['education'].value_counts() < 2].index

df['education'] = df['education'].replace(rare, 'Other')
df['education']

0     BTech
1       MBA
2       MCA
3       BSc
4        BA
5     BTech
6       MBA
7       MCA
8       BSc
9        BA
10    BTech
11      MBA
12      MCA
13      BSc
14       BA
15    BTech
16      MBA
17      MCA
18      BSc
19       BA
Name: education, dtype: str

In [5]:
# Convert gender into numeric format.

df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})
df['gender']

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0
8     1
9     0
10    1
11    0
12    1
13    0
14    1
15    0
16    1
17    0
18    1
19    0
Name: gender, dtype: int64

In [6]:
# Replace salary values greater than 1,50,000 with 1,50,000.

df['salary'] = df['salary'].clip(upper=150000)
df['salary']

0      45000.0
1      55000.0
2          NaN
3      60000.0
4     150000.0
5      50000.0
6      92000.0
7      67000.0
8      48000.0
9      90000.0
10     76000.0
11     51000.0
12     35000.0
13     98000.0
14     66000.0
15     43000.0
16     95000.0
17     72000.0
18     58000.0
19     84000.0
Name: salary, dtype: float64

In [7]:
# Create age group column using apply.

df['age_group'] = df['age'].apply(lambda x: 'Young' if x < 30 else 'Middle' if x < 50 else 'Senior')
df['age_group']

0      Young
1     Middle
2     Middle
3      Young
4     Middle
5      Young
6     Middle
7     Senior
8     Senior
9      Young
10    Middle
11    Middle
12     Young
13    Senior
14    Middle
15     Young
16    Middle
17    Middle
18    Middle
19    Middle
Name: age_group, dtype: str

In [8]:
# Create performance label using rating.

df['performance'] = df['rating'].apply(lambda x: 'Low' if x < 3 else 'Average' if x < 4 else 'High')
df['performance']

0        High
1     Average
2        High
3        High
4        High
5        High
6     Average
7        High
8     Average
9        High
10       High
11    Average
12    Average
13       High
14       High
15    Average
16       High
17       High
18    Average
19       High
Name: performance, dtype: str

In [9]:
# Create salary slab using lambda.

df['salary_slab'] = df['salary'].apply(lambda x: 'Low' if x < 30000 else 'Medium' if x < 70000 else 'High')
df['salary_slab']

0     Medium
1     Medium
2       High
3     Medium
4       High
5     Medium
6       High
7     Medium
8     Medium
9       High
10      High
11    Medium
12    Medium
13      High
14    Medium
15    Medium
16      High
17      High
18    Medium
19      High
Name: salary_slab, dtype: str

In [10]:
# Replace negative values if any with 0.

num_cols = df.select_dtypes(include='number').columns

df[num_cols] = df[num_cols].clip(lower=0)
df[num_cols]

,id,age,gender,salary,experience,rating,projects,leaves_taken,bonus_percent
0,1,25.0,1,45000.0,2,4.2,3.0,5.0,10.0
1,2,32.0,0,55000.0,5,3.8,5.0,10.0,12.0
2,3,41.0,1,NaN,8,4.5,6.0,7.0,15.0
3,4,29.0,0,60000.0,3,NaN,4.0,3.0,9.0
4,5,36.0,1,150000.0,10,4.8,7.0,12.0,18.0
5,6,27.0,0,50000.0,4,4.1,2.0,6.0,0.0
6,7,45.0,1,92000.0,11,3.9,8.0,8.0,14.0
7,8,52.0,0,67000.0,6,4.3,5.0,4.0,10.0
8,9,NaN,1,48000.0,2,3.5,3.0,2.0,8.0
9,10,28.0,0,90000.0,12,8.0,30.0,11.0,17.0
10,11,40.0,1,76000.0,7,4.4,6.0,9.0,16.0
11,12,34.0,0,51000.0,5,3.7,4.0,NaN,12.0
12,13,23.0,1,35000.0,1,3.3,2.0,1.0,7.0
13,14,110.0,0,98000.0,15,4.9,8.0,13.0,20.0
14,15,37.0,1,66000.0,9,4.0,5.0,7.0,13.0
15,16,26.0,0,43000.0,3,3.6,3.0,3.0,9.0
16,17,48.0,1,95000.0,14,4.6,7.0,12.0,19.0
17,18,39.0,0,72000.0,8,4.1,NaN,8.0,15.0
18,19,30.0,1,58000.0,4,3.9,4.0,4.0,11.0
19,20,33.0,0,84000.0,13,4.2,9.0,10.0,0.0

In [11]:
# Create combined city-department column.

df['city_department'] = df['city'].astype(str) + '_' + df['department'].astype(str)
df['city_department']

0     Delhi_Information Technology
1                        Mumbai_HR
2                  Kolkata_Finance
3                Chennai_Marketing
4                  Bangalore_Admin
5     Delhi_Information Technology
6                        Mumbai_HR
7                  Kolkata_Finance
8                Chennai_Marketing
9                  Bangalore_Admin
10    Delhi_Information Technology
11                       Mumbai_HR
12                 Kolkata_Finance
13               Chennai_Marketing
14                 Bangalore_Admin
15    Delhi_Information Technology
16                       Mumbai_HR
17                 Kolkata_Finance
18               Chennai_Marketing
19                 Bangalore_Admin
Name: city_department, dtype: str

In [12]:
# Replace marital status with binary values.

df['marital_status'] = df['marital_status'].map({'Married': 1, 'Single': 0})
df['marital_status']

0     0
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
Name: marital_status, dtype: int64

In [13]:
# Replace project count outliers using median.

Q1 = df['projects'].quantile(0.25)
Q3 = df['projects'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

median_val = df['projects'].median()

df.loc[(df['projects'] < lower) | (df['projects'] > upper), 'projects'] = median_val
median_val

np.float64(5.0)

In [14]:
# Replace education values using dictionary mapping.

mapping = {'Bachelors': 'UG','Masters': 'PG','PhD': 'Doctorate'}
df['education'] = df['education'].map(mapping)
df['education']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
15    NaN
16    NaN
17    NaN
18    NaN
19    NaN
Name: education, dtype: str

In [15]:
# Apply row-wise condition on salary and experience.

df['category'] = df.apply(
    lambda x: 'High' if (x['salary'] > 70000 and x['experience'] > 5) else 'Low',
    axis=1)

df['category']

0      Low
1      Low
2      Low
3      Low
4     High
5      Low
6     High
7      Low
8      Low
9     High
10    High
11     Low
12     Low
13    High
14     Low
15     Low
16    High
17    High
18     Low
19    High
Name: category, dtype: str

In [16]:
# Create salary after bonus column.

df['salary_after_bonus'] = df['salary'] + (df['salary'] * df['bonus_percent'] / 100)
df['salary_after_bonus']

0      49500.0
1      61600.0
2          NaN
3      65400.0
4     177000.0
5      50000.0
6     104880.0
7      73700.0
8      51840.0
9     105300.0
10     88160.0
11     57120.0
12     37450.0
13    117600.0
14     74580.0
15     46870.0
16    113050.0
17     82800.0
18     64380.0
19     84000.0
Name: salary_after_bonus, dtype: float64

## Section I: GroupBy & Aggregation (116–135)

* Performed grouped data summaries to uncover deeper patterns and trends.

* Executed industry-standard analytics practices to support robust data reporting.

In [17]:
# Calculate average salary per department.

df.groupby('department', observed=True)['salary'].mean()

department
Admin                     97500.0
Finance                   58000.0
HR                        73250.0
Information Technology    53500.0
Marketing                 66000.0
Name: salary, dtype: float64

In [18]:
# Calculate total projects per department.

df.groupby('department', observed=True)['projects'].sum()

department
Admin                     26.0
Finance                   13.0
HR                        24.0
Information Technology    14.0
Marketing                 19.0
Name: projects, dtype: float64

In [19]:
# Calculate average rating per city.

df.groupby('city')['rating'].mean()

city
Bangalore    5.250
Chennai      4.100
Delhi        4.075
Kolkata      4.050
Mumbai       4.000
Name: rating, dtype: float64

In [20]:
# Count employees per department.

df.groupby('department', observed=True)['id'].count()

department
Admin                     4
Finance                   4
HR                        4
Information Technology    4
Marketing                 4
Name: id, dtype: int64

In [21]:
# Calculate department-wise max salary.

df.groupby('department', observed=True)['salary'].max()

department
Admin                     150000.0
Finance                    72000.0
HR                         95000.0
Information Technology     76000.0
Marketing                  98000.0
Name: salary, dtype: float64

In [22]:
# Calculate department-wise min experience.

df.groupby('department', observed=True)['experience'].min()

department
Admin                     9
Finance                   1
HR                        5
Information Technology    2
Marketing                 2
Name: experience, dtype: int64

In [23]:
# Calculate city-wise average bonus percent.

df.groupby('city')['bonus_percent'].mean()

city
Bangalore    12.00
Chennai      12.00
Delhi         8.75
Kolkata      11.75
Mumbai       14.25
Name: bonus_percent, dtype: float64

In [24]:
# Group by department and city together.

df.groupby(['department', 'city'], observed=True).size()

department              city
Admin                   Bangalore    4
Finance                 Kolkata      4
HR                      Mumbai       4
Information Technology  Delhi        4
Marketing               Chennai      4
dtype: int64

In [25]:
# Find department with highest average salary.

df.groupby('department', observed=True)['salary'].mean().idxmax()

'Admin'

In [26]:
# Find city with lowest average rating.

df.groupby('city')['rating'].mean().idxmin()

'Mumbai'

In [27]:
# Group-wise missing value count.

df.groupby('department', observed=True).agg(lambda x: x.isnull().sum())

,id,name,age,gender,city,salary,experience,rating,is_active,projects,leaves_taken,bonus_percent,education,marital_status,age_group,performance,salary_slab,city_department,category,salary_after_bonus
department,,,,,,,,,,,,,,,,,,,,
Admin,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0
Finance,0,0,0,0,0,1,0,0,0,1,0,0,4,0,0,0,0,0,0,1
HR,0,0,0,0,0,0,0,0,0,0,1,0,4,0,0,0,0,0,0,0
Information Technology,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0
Marketing,0,0,1,0,0,0,0,1,0,0,0,0,4,0,0,0,0,0,0,0

In [28]:
# Group-wise salary standard deviation.

df.groupby('department', observed=True)['salary'].std()

department
Admin                     36455.452267
Finance                   20074.859900
HR                        23471.614062
Information Technology    15286.159317
Marketing                 21969.676071
Name: salary, dtype: float64

In [29]:
# Group-wise median salary.

df.groupby('department', observed=True)['salary'].median()

department
Admin                     87000.0
Finance                   67000.0
HR                        73500.0
Information Technology    47500.0
Marketing                 59000.0
Name: salary, dtype: float64

In [30]:
# Calculate department-wise salary range.

df.groupby('department', observed=True)['salary'].agg(lambda x: x.max() - x.min())

department
Admin                     84000.0
Finance                   37000.0
HR                        44000.0
Information Technology    33000.0
Marketing                 50000.0
Name: salary, dtype: float64

In [31]:
# Find top-paid employee per department.

df.loc[df.groupby('department', observed=True)['salary'].idxmax()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,leaves_taken,bonus_percent,education,marital_status,age_group,performance,salary_slab,city_department,category,salary_after_bonus
4,5,Person_5,36.0,1,Bangalore,150000.0,Admin,10,4.8,False,...,12.0,18.0,NaN,0,Middle,High,High,Bangalore_Admin,High,177000.0
17,18,Person_18,39.0,0,Kolkata,72000.0,Finance,8,4.1,True,...,8.0,15.0,NaN,1,Middle,High,High,Kolkata_Finance,High,82800.0
16,17,Person_17,48.0,1,Mumbai,95000.0,HR,14,4.6,False,...,12.0,19.0,NaN,0,Middle,High,High,Mumbai_HR,High,113050.0
10,11,Person_11,40.0,1,Delhi,76000.0,Information Technology,7,4.4,True,...,9.0,16.0,NaN,0,Middle,High,High,Delhi_Information Technology,High,88160.0
13,14,Person_14,110.0,0,Chennai,98000.0,Marketing,15,4.9,True,...,13.0,20.0,NaN,1,Senior,High,High,Chennai_Marketing,High,117600.0

In [32]:
# Find least experienced employee per city.

df.loc[df.groupby('city')['experience'].idxmin()]

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,leaves_taken,bonus_percent,education,marital_status,age_group,performance,salary_slab,city_department,category,salary_after_bonus
14,15,Person_15,37.0,1,Bangalore,66000.0,Admin,9,4.0,False,...,7.0,13.0,NaN,0,Middle,High,Medium,Bangalore_Admin,Low,74580.0
8,9,Person_9,NaN,1,Chennai,48000.0,Marketing,2,3.5,False,...,2.0,8.0,NaN,0,Senior,Average,Medium,Chennai_Marketing,Low,51840.0
0,1,Person_1,25.0,1,Delhi,45000.0,Information Technology,2,4.2,True,...,5.0,10.0,NaN,0,Young,High,Medium,Delhi_Information Technology,Low,49500.0
12,13,Person_13,23.0,1,Kolkata,35000.0,Finance,1,3.3,True,...,1.0,7.0,NaN,0,Young,Average,Medium,Kolkata_Finance,Low,37450.0
1,2,Person_2,32.0,0,Mumbai,55000.0,HR,5,3.8,False,...,10.0,12.0,NaN,1,Middle,Average,Medium,Mumbai_HR,Low,61600.0

In [33]:
# Calculate salary contribution percentage per city.

df['city_salary_pct'] = df['salary'] / df['salary'].sum() * 100
df['city_salary_pct']

0      3.370787
1      4.119850
2           NaN
3      4.494382
4     11.235955
5      3.745318
6      6.891386
7      5.018727
8      3.595506
9      6.741573
10     5.692884
11     3.820225
12     2.621723
13     7.340824
14     4.943820
15     3.220974
16     7.116105
17     5.393258
18     4.344569
19     6.292135
Name: city_salary_pct, dtype: float64

In [34]:
# Group-wise normalization of salary.

df['salary_normalized'] = df.groupby('department', observed=True)['salary'].transform(
    lambda x: (x - x.min()) / (x.max() - x.min()))
df['salary_normalized']

0     0.060606
1     0.090909
2          NaN
3     0.240000
4     1.000000
5     0.212121
6     0.931818
7     0.864865
8     0.000000
9     0.285714
10    1.000000
11    0.000000
12    0.000000
13    1.000000
14    0.000000
15    0.000000
16    1.000000
17    1.000000
18    0.200000
19    0.214286
Name: salary_normalized, dtype: float64

In [35]:
# Department-wise cumulative employee count.

df['dept_cum_count'] = df.groupby('department', observed=True).cumcount() + 1
df['dept_cum_count']

0     1
1     1
2     1
3     1
4     1
5     2
6     2
7     2
8     2
9     2
10    3
11    3
12    3
13    3
14    3
15    4
16    4
17    4
18    4
19    4
Name: dept_cum_count, dtype: int64

In [36]:
# Group-wise outlier detection for salary.

def detect_outliers(group):
    Q1 = group['salary'].quantile(0.25)
    Q3 = group['salary'].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return group[(group['salary'] < lower) | (group['salary'] > upper)]

df.groupby('department', observed=True, group_keys=False)\
  .apply(detect_outliers, include_groups=False)

,id,name,age,gender,city,salary,experience,rating,is_active,projects,...,marital_status,age_group,performance,salary_slab,city_department,category,salary_after_bonus,city_salary_pct,salary_normalized,dept_cum_count
4,5,Person_5,36.0,1,Bangalore,150000.0,10,4.8,False,7.0,...,0,Middle,High,High,Bangalore_Admin,High,177000.0,11.235955,1.0,1
10,11,Person_11,40.0,1,Delhi,76000.0,7,4.4,True,6.0,...,0,Middle,High,High,Delhi_Information Technology,High,88160.0,5.692884,1.0,3
13,14,Person_14,110.0,0,Chennai,98000.0,15,4.9,True,8.0,...,1,Senior,High,High,Chennai_Marketing,High,117600.0,7.340824,1.0,3

## Section J: Binning using pd.cut / pd.qcut (136–145)

* Discretized continuous numerical features into categorical bins.

* Optimized analytical workflows and enhanced the effectiveness of visual data representations.

In [37]:
# Create salary bins using pd.cut.

df['salary_bin'] = pd.cut(df['salary'], bins=3)
df['salary_bin']

0        (34885.0, 73333.333]
1        (34885.0, 73333.333]
2                         NaN
3        (34885.0, 73333.333]
4      (111666.667, 150000.0]
5        (34885.0, 73333.333]
6     (73333.333, 111666.667]
7        (34885.0, 73333.333]
8        (34885.0, 73333.333]
9     (73333.333, 111666.667]
10    (73333.333, 111666.667]
11       (34885.0, 73333.333]
12       (34885.0, 73333.333]
13    (73333.333, 111666.667]
14       (34885.0, 73333.333]
15       (34885.0, 73333.333]
16    (73333.333, 111666.667]
17       (34885.0, 73333.333]
18       (34885.0, 73333.333]
19    (73333.333, 111666.667]
Name: salary_bin, dtype: category
Categories (3, interval[float64, right]): [(34885.0, 73333.333] < (73333.333, 111666.667] < (111666.667, 150000.0]]

In [38]:
# Label salary bins as Low, Medium, High.

df['salary_bin'] = pd.cut(df['salary'], bins=3, labels=['Low', 'Medium', 'High'])
df['salary_bin']

0        Low
1        Low
2        NaN
3        Low
4       High
5        Low
6     Medium
7        Low
8        Low
9     Medium
10    Medium
11       Low
12       Low
13    Medium
14       Low
15       Low
16    Medium
17       Low
18       Low
19    Medium
Name: salary_bin, dtype: category
Categories (3, str): ['Low' < 'Medium' < 'High']

In [39]:
# Create age groups using fixed bins.

df['age_group'] = pd.cut(df['age'], bins=[0, 30, 50, 100], labels=['Young', 'Middle', 'Senior'])
df['age_group']

0      Young
1     Middle
2     Middle
3      Young
4     Middle
5      Young
6     Middle
7     Senior
8        NaN
9      Young
10    Middle
11    Middle
12     Young
13       NaN
14    Middle
15     Young
16    Middle
17    Middle
18     Young
19    Middle
Name: age_group, dtype: category
Categories (3, str): ['Young' < 'Middle' < 'Senior']

In [40]:
# Create experience quartiles using pd.qcut.

df['exp_quartile'] = pd.qcut(df['experience'], q=4)
df['exp_quartile']

0     (0.999, 3.75]
1       (3.75, 6.5]
2      (6.5, 10.25]
3     (0.999, 3.75]
4      (6.5, 10.25]
5       (3.75, 6.5]
6     (10.25, 15.0]
7       (3.75, 6.5]
8     (0.999, 3.75]
9     (10.25, 15.0]
10     (6.5, 10.25]
11      (3.75, 6.5]
12    (0.999, 3.75]
13    (10.25, 15.0]
14     (6.5, 10.25]
15    (0.999, 3.75]
16    (10.25, 15.0]
17     (6.5, 10.25]
18      (3.75, 6.5]
19    (10.25, 15.0]
Name: exp_quartile, dtype: category
Categories (4, interval[float64, right]): [(0.999, 3.75] < (3.75, 6.5] < (6.5, 10.25] < (10.25, 15.0]]

In [41]:
# Compare bin sizes from cut vs qcut.

# Count from cut
cut_counts = df['salary_bin'].value_counts()

# Count from qcut
qcut_counts = pd.qcut(df['salary'], q=3).value_counts()

cut_counts, qcut_counts

(salary_bin
 Low       12
 Medium     6
 High       1
 Name: count, dtype: int64,
 salary
 (34999.999, 55000.0]    7
 (55000.0, 76000.0]      6
 (76000.0, 150000.0]     6
 Name: count, dtype: int64)

In [42]:
# Identify highest salary bin employees.

df[df['salary_bin'] == 'High']

,id,name,age,gender,city,salary,department,experience,rating,is_active,...,performance,salary_slab,city_department,category,salary_after_bonus,city_salary_pct,salary_normalized,dept_cum_count,salary_bin,exp_quartile
4,5,Person_5,36.0,1,Bangalore,150000.0,Admin,10,4.8,False,...,High,High,Bangalore_Admin,High,177000.0,11.235955,1.0,1,High,"(6.5, 10.25]"

In [43]:
# Create project workload bins.

df['project_workload'] = pd.cut(df['projects'], bins=3, labels=['Low', 'Medium', 'High'])
df['project_workload']

0        Low
1     Medium
2     Medium
3        Low
4       High
5        Low
6       High
7     Medium
8        Low
9     Medium
10    Medium
11       Low
12       Low
13      High
14    Medium
15       Low
16      High
17       NaN
18       Low
19      High
Name: project_workload, dtype: category
Categories (3, str): ['Low' < 'Medium' < 'High']